"""Add status and priority fields to contact messages

Revision ID: 79a72dfd318b
Revises: 35d6cfc1b630
Create Date: 2026-01-25 21:43:06.917416

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79a72dfd318b'
down_revision = '35d6cfc1b630'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contact_messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_read', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('read_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('is_archived', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('priority', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contact_messages', schema=None) as batch_op:
        batch_op.drop_column('updated_at')
        batch_op.drop_column('priority')
        batch_op.drop_column('status')
        batch_op.drop_column('is_archived')
        batch_op.drop_column('read_at')
        batch_op.drop_column('is_read')

    # ### end Alembic commands ###
