"""Add is_admin column

Revision ID: 875c76e047f0
Revises: 
Create Date: 2025-08-25 10:45:58.690027

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '875c76e047f0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Only apply changes to events table since career_applications doesn't exist
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')
        batch_op.drop_column('location')

    # ### end Alembic commands ###
