"""Add last_activity field to chatbot conversations

Revision ID: feace478ed95
Revises: 8982f46fc4b0
Create Date: 2026-01-25 21:45:51.962660

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'feace478ed95'
down_revision = '8982f46fc4b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chatbot_conversations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_activity', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chatbot_conversations', schema=None) as batch_op:
        batch_op.drop_column('last_activity')

    # ### end Alembic commands ###
